### ISSUE TITLE
Invalid templates for Customer Maintenance and Customer - Orders screens

### ISSUE THREAD

**Issue by radu2501** [consultingwerk/SmartComponentsAngularDemo#4]
@mikefechner, the customer maintenance and customer - orders screens have invalid templates and crash at runtime when compiling the dynamic smart forms. Both have the following error in their templates:

![image](https://user-images.githubusercontent.com/6839451/32663022-2ab99650-c635-11e7-9122-ffaaac87b878.png)

Note the extra quotation mark before `col-xs-12`. That causes the JiT compiler to crash with an "unexpected closing tag" error.

**Comment by mikefechner** [comment]
Since when?

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Radu Nicoara <notifications@github.com>
Gesendet: 10.11.2017 15:41
An: consultingwerk/SmartComponentsAngularDemo
Cc: Mike Fechner; Mention
Betreff: [consultingwerk/SmartComponentsAngularDemo] Invalid templates for Customer Maintenance and Customer - Orders screens (#4)


@mikefechner<https://github.com/mikefechner>, the customer maintenance and customer - orders screens have invalid templates and crash at runtime when compiling the dynamic smart forms. Both have the following error in their templates:

[image]<https://user-images.githubusercontent.com/6839451/32663022-2ab99650-c635-11e7-9122-ffaaac87b878.png>

Note the extra quotation mark before col-xs-12. That causes the JiT compiler to crash with an "unexpected closing tag" error.

**Comment by radu2501** [comment]
I only just noticed it.

**Comment by mikefechner** [comment]
> Since when?

14/10/2017 :-(

Fixing it now.

**Comment by mikefechner** [comment]
@radu2501 Should be fixed now. 

Please close the ticket when you confirm.

**Comment by radu2501** [comment]
Almost there:

![image](https://user-images.githubusercontent.com/6839451/32721629-c5b794fe-c86f-11e7-8552-6b6f4bc3fd2a.png)

As you can see, the left and right pane contents do not fill the whole available space (on medium and large screens).

![image](https://user-images.githubusercontent.com/6839451/32721583-9e4c5c9c-c86f-11e7-933e-b38efc08a3ea.png)

To fix this:

```
<div class="col-xs-12 col-md-6" left-pane>
```

should become

```
<div class="col-xs-12" left-pane>
```

The same goes for the right pane. This is because the split view is now controlling the width. `col-xs-12` is fine, because it essentially means "for any screen size bigger than or equal to 'extra small', fill the available space". `col-md-6` means "although, when you get to medium screens, only fill half of the available space". This was necessary when we did not have the split pane and the "available space" was determined by the actual browser window. But now, `col-md-6` translates to "on medium screens and above, only fill half of the space that my parent split pane has provided me".

**Comment by mikefechner** [comment]
Fixed.

Von: Radu Nicoara [mailto:notifications@github.com]
Gesendet: Montag, 13. November 2017 11:47
An: consultingwerk/SmartComponentsAngularDemo <SmartComponentsAngularDemo@noreply.github.com>
Cc: Mike Fechner <mike.fechner@consultingwerk.de>; Mention <mention@noreply.github.com>
Betreff: Re: [consultingwerk/SmartComponentsAngularDemo] Invalid templates for Customer Maintenance and Customer - Orders screens (#4)


Almost there:

[image]<https://user-images.githubusercontent.com/6839451/32721629-c5b794fe-c86f-11e7-8552-6b6f4bc3fd2a.png>

As you can see, the left and right pane contents do not fill the whole available space (on medium and large screens).

[image]<https://user-images.githubusercontent.com/6839451/32721583-9e4c5c9c-c86f-11e7-933e-b38efc08a3ea.png>

To fix this:

<div class="col-xs-12 col-md-6" left-pane>

should become

<div class="col-xs-12" left-pane>

The same goes for the right pane. This is because the split view is now controlling the width. col-xs-12 is fine, because it essentially means "for any screen size bigger than or equal to 'extra small', fill the available space". col-md-6 means "although, when you get to medium screens, only fill half of the available space". This was necessary when we did not have the split pane and the "available space" was determined by the actual browser window. But now, col-md-6 translates to "on medium screens and above, only fill half of the space that my parent split pane has provided me".

**Comment by radu2501** [comment]
Confirmed
